project_name: 大脑一本账

env: 测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 冯爱军

# 域名1
host: http://dev-bl.zj.gov.cn:18080
# 域名2，支持多个域名配置
app_host:

# 运行完后直接打开Allure报告
allure_open_switch: True

# 报告通知类型：0: 不发送通知 1：钉钉 2、邮箱通知
notification_type: 1

# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: True

# 钉钉相关配置，一定要改！改！改！自己的！
ding_talk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=002e6fe210e5b207765de2d47205c61cea5f69a7188262c12339f483e4abb6f8
  secret: SEC2f51cd336886b52aaa4a45b6a5a3d63af2eaefad35ab1a03af96323ee41c3cef
# 数据库相关配置
mysql_db:
  # 数据库开关
  A:
    switch: False
    host: 172.31.75.156
    user: yqfk_2022_cs
    password: Fs4vnWJNcrMkmqJeMHdbQwjJtPtocoeb82vzrYtmhqC2/rqGSg1FVCiorirzS1H5Keb/18TxPXizyHWlUgWuZOJLUUYTs8oPV+DB7yiXcG2jIe5G/45w3q7uZNMo8jJ5O8q22h9ywp7CvnFFctAOnOnilr33WFUOaQfJJwWWVz4=
    port: 3306
  DNYBZ:
    switch: True
    host: 10.145.6.12
    user: admin
    password: BZjK0IYZavm0DVC/x9Tag8x6cUs5kRn6J5kKrilYbNXLqquL4rVY5Y48TgrdlGhEjcPEoqysGesQz7pjftkv10fwwOe/glnBuMJustn00MgilgLiu1QLlk0xLFqA8uvi7l7njsdf5z4HLMtJTcYk/Q36Nx1HKsyrLqz44nT90sM=
    port: 3306
# Redis相关配置
redis:
  # 开关
  switch: False
  host: 0.0.0.0
  port: 18000
  database: 0
  password: Tn0Bi/rxkLwM9BeN1ytZzZEYBbpD3KHJRONDcz8gXjDalXf3Mcef3FB3WTLTAlLR6IvTqu6oApOI7cTgB8bTkOcMAngoMYdBHbrRxO/T5fQf19UqnZkd/LoE7pai9trwnZBrfNevOtj+daHkWZ0IeVOQB3WV5rYB8ilBSY9BIqU=


# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/


### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
email:
  switch: False
  send_user:
  email_host: smtp.qq.com
  # 自己到QQ邮箱中配置stamp_key
  stamp_key:
  # 收件人改成自己的邮箱
  send_list:




